# Split String

In [ ]:
Ducati = "Ducati motorad will take place in Dubai"
Ducati.split()

# Formatted string

In [4]:
Planet = "Earth"
Diameter = 12472
print(f"The diameter of {Planet} is {Diameter} kilometers")

The diameter of Earth is 12472 kilometers


# Nested Dictionary

In [5]:
nested = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}
print(nested["k1"][3]["tricky"][3]["target"][3]) 

hello


# Numpy

In [11]:
import numpy as numpy

# Array of zeros

In [12]:
numpy = numpy.zeros(10)
numpy

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

# Array of even integers

In [18]:
import numpy as np

In [19]:
var2=np.arange(20,36,2)
print(var2)

[20 22 24 26 28 30 32 34]


# 3x3 matrix

In [20]:
np_matrix = np.arange(0,9).reshape(3,3) 
np_matrix

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

# Concatenate two array

In [21]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
np.concatenate((a,b),axis=None)

array([1, 2, 3, 4, 5, 6])

# Dataframe

In [22]:
import pandas as pd
A = np.random.randint(10, size=(3,2))
df = pd.DataFrame(A,columns=['cola', 'colb'])
df

cola  colb
0     4     3
1     6     6
2     2     0

# Series of Dates

In [24]:
import pandas as pd
  
df = pd.DataFrame()
df['time'] = pd.date_range(start="1/1/2023",end="2/10/2023", freq ='24H')
df['year'] = df['time'].dt.year
df['month'] = df['time'].dt.month
df['day'] = df['time'].dt.day

df.head()

time  year  month  day
0 2023-01-01  2023      1    1
1 2023-01-02  2023      1    2
2 2023-01-03  2023      1    3
3 2023-01-04  2023      1    4
4 2023-01-05  2023      1    5

# 2D list to dataframe

In [25]:
lists = [[1, 'aaa', 22], [2, 'bbb', 25], [3, 'ccc', 24]]
df = pd.DataFrame(lists, columns =['col1',"col2","col3"]) 
df

col1 col2  col3
0     1  aaa    22
1     2  bbb    25
2     3  ccc    24